package com.ums.management.core.dao;

import com.ums.management.core.model.DictType;

import java.util.List;

public interface DictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    int insert(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    int insertSelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    DictType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    int updateByPrimaryKeySelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    int updateByPrimaryKey(DictType record);

    List<DictType> selectDictTypes();
}