package com.ums.management.core.dao;

import com.ums.management.core.model.FileMeta;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FileMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    int insert(FileMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    int insertSelective(FileMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    FileMeta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    int updateByPrimaryKeySelective(FileMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_meta
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    int updateByPrimaryKey(FileMeta record);

    List<FileMeta> selectAll(@Param("name") String name, @Param("type") String type, @Param("start") int start, @Param("rows") int rows);
    int countAll();
}