package com.ums.management.core.dao;

import com.ums.management.core.model.L10n;

import java.util.List;

public interface L10nMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    int insert(L10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    int insertSelective(L10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    L10n selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    int updateByPrimaryKeySelective(L10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l10n
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    int updateByPrimaryKey(L10n record);

    List<L10n> selectL10ns();
}