package com.ums.management.core.dao;

import com.ums.management.core.model.LocalDict;
import org.springframework.cglib.core.Local;

import java.util.List;
import java.util.Map;

public interface LocalDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    int insert(LocalDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    int insertSelective(LocalDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    LocalDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    int updateByPrimaryKeySelective(LocalDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_dict
     *
     * @mbggenerated Wed Apr 12 16:03:26 CST 2017
     */
    int updateByPrimaryKey(LocalDict record);

    List<LocalDict> selectLocalDicts(Map<String, Object> queryMap);

    List<LocalDict> selectLocalDictByCodeAndOrgId(Map<String, Object> queryMap);
}