package com.ums.management.core.dao;

import com.ums.management.core.model.MsgL10n;

import java.util.List;
import java.util.Map;

public interface MsgL10nMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    int insert(MsgL10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    int insertSelective(MsgL10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    MsgL10n selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    int updateByPrimaryKeySelective(MsgL10n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_l10n
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    int updateByPrimaryKey(MsgL10n record);

    List<MsgL10n> selectPackage(String code);
    List<MsgL10n> selectByMsg(String msg);

    List<MsgL10n> selectMsgL10ns(Map<String, Object> queryMap);
    Integer countMsgL10ns(Map<String, Object> queryMap);

    void deleteByMsg(String msg);
}