package com.ums.management.core.dao;

import com.ums.management.core.model.Organization;

import java.util.List;
import java.util.Map;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    Organization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Apr 04 17:33:05 CST 2017
     */
    int updateByPrimaryKey(Organization record);

    List<Organization> selectOrganizations(Map<String, Object> queryMap);

    int countOrganizations(Map<String, Object> queryMap);

    List<Organization> selectOrganizationsByUserId(Map<String, Object> queryMap);

    int countOrganizationsByUserId(Map<String, Object> queryMap);
}