package com.ums.management.core.dao;

import com.ums.management.core.model.RoleMenu;

import java.util.List;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    int updateByPrimaryKey(RoleMenu record);

    List<RoleMenu> selectByRoleId(Integer id);

    void deleteByRoleId(int id);
}