package com.ums.management.core.dao;

import com.ums.management.core.model.Submenu;

import java.util.List;

public interface SubmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    int insert(Submenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    int insertSelective(Submenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    Submenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    int updateByPrimaryKeySelective(Submenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    int updateByPrimaryKey(Submenu record);


    List<Submenu> selectSubmenus();
}