package com.ums.management.core.dao;

import com.ums.management.core.model.UserExt;

public interface UserExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    int insert(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    int insertSelective(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    UserExt selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    int updateByPrimaryKeySelective(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext
     *
     * @mbggenerated Thu Mar 15 22:50:33 CST 2018
     */
    int updateByPrimaryKey(UserExt record);
}