package com.ums.management.core.dao;

import com.ums.management.core.model.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 04 11:10:54 CST 2017
     */
    int updateByPrimaryKey(User record);

    List<User> selectAllUsers(Map<String, Object> queryMap);
    long countAllUsers(Map<String, Object> queryMap);

    User selectByCode(String code);

    List<User> selectAllUsersByUserId(Map<String, Object> queryMap);
    long countAllUsersByUserId(Map<String, Object> queryMap);

}