l10n.addResource('en_us', {
    "Home": "Home",
    "Help": "Help",
    "User": "User",
    "Role": "Role",
    "Organization": "Organization",
    "Menu": "Menu",
    "Settings": "Settings",
    "Password": "Password",
    "Global Dictionary": "Global Dictionary",
    "Local Dictionary": "Local Dictionary",
    "System Management": "System Management",
    "System Configuration": "System Configuration",
    "User Settings": "User Settings",
    "Select Organization": "Select Organization",
    "Generic Platform": "Generic Platform",
    "Global": "Global",
    "Total": "Total",
    "Item(s)": "Item(s)",
    "Page(s)": "Page(s)",
    "Go": "Go",
    "About": "About",
    "Confirm": "Confirm",
    "Delete": "Delete",
    "Version": "Version",
    "Language": "Language",
    "None": "N/A",
    "Save": "Save",
    "Time": "Time",
    "Status": "Status",
    "Search": "Search",
    "Input Password": "Input Password",
    "Authentication Fail": "Authentication Fail",
    "Password Setting": "Password Setting",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "New Password Again": "New Password Again",
    "New password mismatch": "New password mismatch",
    "Password can't be empty": "Password can't be empty",
    "Password min length": "Password length must great then 6",
    "Save success": "Save success",
    "Apply": "Apply",
    "OK": "OK",
    "Cancel": "Cancel",
    "Can't create Admin user": "Can't create Admin user",
    "Can't edit Admin user": "Can't edit Admin user",
    "Can't delete Admin user": "Can't delete Admin user",
    "Can't delete current user": "Can't delete current user",
    "Can't reset password for Admin user": "Can't reset password for Admin user",
    "Can't edit Admin role": "Can't edit Admin role",
    "Admin role can't be removed": "Admin role can't be removed",
    "Please Select": "Please Select",
    "Logout": "Logout",
    "UserRole": "User's Role",
    "Success": "Success",
    "Error": "Error",
    "Server Side Error": "Server Side Error",
    "Warning": "Warning",
    "Attention": "Attention",
    "Unknown": "Unknown",
    "ms": "ms",
    "TimeZone": "Time Zone",
    "MessageCount": "Message Count",
    "Frequency": "Frequency"
});