l10n.addResource('en_us', {
    "Home": "Home",
    "Overview": "Overview",
    "Help": "Help",
    "Settings": "Settings",
    "Forms": "Forms",
    "Management": "Management",
    "Dashboard": "Dashboard",
    "Messages": "Messages",
    "Password": "Password",
    "Generic Platform": "Generic Platform",
    "Global": "Global",
    "Total": "Total",
    "About": "About",
    "Confirm": "Confirm",
    "Delete": "Delete",
    "Version": "Version",
    "Communication Error": "Communication Error",
    "Language": "Language",
    "None": "N/A",
    "Monitor": "Monitor",
    "Property": "Property",
    "Value": "Value",
    "Save": "Save",
    "Time": "Time",
    "Status": "Status",
    "Search": "Search",
    "Input Password": "Input Password",
    "Authentication Fail": "Authentication Fail",
    "Password Setting": "Password Setting",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "New Password Again": "New Password Again",
    "New password mismatch": "New password mismatch",
    "Password can't be empty": "Password can't be empty",
    "Password min length": "Password length must great then 6",
    "Save success": "Save success",
    "Apply": "Apply",
    "OK": "OK",
    "Cancel": "Cancel",
    "Database": "Database",
    "Service": "System Service",
    "Server": "Server",
    "System Status": "System Status",
    "Dongle": "Dongle",
    "Error": "Error",
    "Warning": "Warning",
    "Unknown": "Unknown",
    "ms": "ms",
    "TimeZone": "Time Zone",
    "MessageCount": "Message Count",
    "Frequency": "Frequency"
});