l10n.addResource('zh_cn', {
    "Home": "首页",
    "Help": "帮助",
    "User": "用户",
    "Role": "角色",
    "Organization": "组织",
    "Menu": "菜单",
    "Settings": "设置",
    "Password": "密码",
    "User Management": "用户管理",
    "System Configuration": "系统配置",
    "User Settings": "用户设置",
    "Select Organization": "选择组织",
    "Generic Platform": "通用平台",
    "Global": "全局",
    "Total": "总共",
    "Item(s)": "项",
    "Page(s)": "页",
    "Go": "跳转",
    "About": "关于",
    "Confirm": "确认",
    "Delete": "删除",
    "Version": "版本",
    "Language": "语言",
    "None": "无效",
    "Save": "保存",
    "Time": "时间",
    "Status": "状态",
    "Search": "查询",
    "Input Password": "输入密码",
    "Authentication Fail": "认证失败",
    "Password Setting": "密码设置",
    "Old Password": "旧密码",
    "New Password": "新密码",
    "New Password Again": "确认新密码",
    "New password mismatch": "新密码不一致",
    "Password can't be empty": "密码不能为空",
    "Password min length": "密码至少6位",
    "Save success": "保存成功",
    "Apply": "应用",
    "OK": "确认",
    "Cancel": "取消",
    "Can't create Admin user": "不能创建管理员",
    "Can't edit Admin user": "不能编辑管理员",
    "Can't delete Admin user": "不能删除管理员",
    "Can't reset password for Admin user": "不能重置管理员密码",
    "Can't edit Admin role": "不能编辑管理员角色",
    "Admin role can't be removed": "管理员角色不能删除",
    "Please Select": "请选择",
    "Logout": "注销",
    "UserRole": "用户角色",
    "System Status": "系统状态",
    "Success": "成功",
    "Error": "错误",
    "Warning": "异常",
    "Attention": "注意",
    "Unknown": "未知",
    "ms": "毫秒",
    "TimeZone": "时区",
    "MessageCount": "消息数量",
    "Frequency": "频率"
});