package com.ums.management.core.model;

public class DictType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.id
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.code
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.name
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.global
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    private Boolean global;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.comment
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.id
     *
     * @return the value of dict_type.id
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.id
     *
     * @param id the value for dict_type.id
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.code
     *
     * @return the value of dict_type.code
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.code
     *
     * @param code the value for dict_type.code
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.name
     *
     * @return the value of dict_type.name
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.name
     *
     * @param name the value for dict_type.name
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.global
     *
     * @return the value of dict_type.global
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public Boolean getGlobal() {
        return global;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.global
     *
     * @param global the value for dict_type.global
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public void setGlobal(Boolean global) {
        this.global = global;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.comment
     *
     * @return the value of dict_type.comment
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.comment
     *
     * @param comment the value for dict_type.comment
     *
     * @mbggenerated Wed Apr 12 11:11:39 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}