package com.ums.management.core.model;

public class DictType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.id
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.name
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_type.global
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    private Boolean global;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.id
     *
     * @return the value of dict_type.id
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.id
     *
     * @param id the value for dict_type.id
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.name
     *
     * @return the value of dict_type.name
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.name
     *
     * @param name the value for dict_type.name
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_type.global
     *
     * @return the value of dict_type.global
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public Boolean getGlobal() {
        return global;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_type.global
     *
     * @param global the value for dict_type.global
     *
     * @mbggenerated Tue Apr 11 22:02:42 CST 2017
     */
    public void setGlobal(Boolean global) {
        this.global = global;
    }
}