package com.ums.management.core.model;

public class FileMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_meta.id
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_meta.name
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_meta.uri
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_meta.type
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_meta.id
     *
     * @return the value of file_meta.id
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_meta.id
     *
     * @param id the value for file_meta.id
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_meta.name
     *
     * @return the value of file_meta.name
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_meta.name
     *
     * @param name the value for file_meta.name
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_meta.uri
     *
     * @return the value of file_meta.uri
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_meta.uri
     *
     * @param uri the value for file_meta.uri
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_meta.type
     *
     * @return the value of file_meta.type
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_meta.type
     *
     * @param type the value for file_meta.type
     *
     * @mbggenerated Mon Apr 24 11:36:26 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}