package com.ums.management.core.model;

public class L10n {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l10n.code
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l10n.description
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l10n.code
     *
     * @return the value of l10n.code
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l10n.code
     *
     * @param code the value for l10n.code
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l10n.description
     *
     * @return the value of l10n.description
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l10n.description
     *
     * @param description the value for l10n.description
     *
     * @mbggenerated Thu Sep 14 13:27:22 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}