package com.ums.management.core.model;

import java.util.ArrayList;
import java.util.BitSet;
import java.util.List;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    private String name;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.display_order
     *
     * @return the value of menu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.display_order
     *
     * @param displayOrder the value for menu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    private List<Submenu> submenus;
    public List<Submenu> getSubmenus() {
        return submenus;
    }

    public void addSubmenu(Submenu sub) {
        if(submenus == null)
            submenus = new ArrayList<Submenu>();
        submenus.add(sub);
    }
}