package com.ums.management.core.model;

public class MsgL10n {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_l10n.id
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_l10n.msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_l10n.code
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_l10n.trans_msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    private String transMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_l10n.id
     *
     * @return the value of msg_l10n.id
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_l10n.id
     *
     * @param id the value for msg_l10n.id
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_l10n.msg
     *
     * @return the value of msg_l10n.msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_l10n.msg
     *
     * @param msg the value for msg_l10n.msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_l10n.code
     *
     * @return the value of msg_l10n.code
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_l10n.code
     *
     * @param code the value for msg_l10n.code
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_l10n.trans_msg
     *
     * @return the value of msg_l10n.trans_msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public String getTransMsg() {
        return transMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_l10n.trans_msg
     *
     * @param transMsg the value for msg_l10n.trans_msg
     *
     * @mbggenerated Thu Sep 14 14:31:41 CST 2017
     */
    public void setTransMsg(String transMsg) {
        this.transMsg = transMsg == null ? null : transMsg.trim();
    }
}