package com.ums.management.core.model;

public class Role {
    private static final String CODE_ADMIN = "Admin";
    private static final String CODE_POWER_USER = "PowerUser";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Name
     *
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Description
     *
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Enabled
     *
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Register
     *
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    private Boolean register;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Name
     *
     * @return the value of role.Name
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Name
     *
     * @param name the value for role.Name
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Description
     *
     * @return the value of role.Description
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Description
     *
     * @param description the value for role.Description
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Enabled
     *
     * @return the value of role.Enabled
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Enabled
     *
     * @param enabled the value for role.Enabled
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Register
     *
     * @return the value of role.Register
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public Boolean getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Register
     *
     * @param register the value for role.Register
     * @mbggenerated Wed Apr 19 14:48:54 CST 2017
     */
    public void setRegister(Boolean register) {
        this.register = register;
    }

    public boolean isAdmin() {
        return this.getName().equals(CODE_ADMIN);
    }

    public boolean isPowerUser() {
        return this.getName().equals(CODE_POWER_USER);
    }
}