package com.ums.management.core.model;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.submenu_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    private Integer submenuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.submenu_id
     *
     * @return the value of role_menu.submenu_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public Integer getSubmenuId() {
        return submenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.submenu_id
     *
     * @param submenuId the value for role_menu.submenu_id
     *
     * @mbggenerated Sat Apr 01 17:58:26 CST 2017
     */
    public void setSubmenuId(Integer submenuId) {
        this.submenuId = submenuId;
    }
}