package com.ums.management.core.model;

public class Submenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.name
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.link
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    private String link;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    private String icon;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.parent_id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.id
     *
     * @return the value of submenu.id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.id
     *
     * @param id the value for submenu.id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.name
     *
     * @return the value of submenu.name
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.name
     *
     * @param name the value for submenu.name
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbggenerated Sat Apr 01 17:57:20 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.link
     *
     * @return the value of submenu.link
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.link
     *
     * @param link the value for submenu.link
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.parent_id
     *
     * @return the value of submenu.parent_id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.parent_id
     *
     * @param parentId the value for submenu.parent_id
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.display_order
     *
     * @return the value of submenu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.display_order
     *
     * @param displayOrder the value for submenu.display_order
     *
     * @mbggenerated Sat Apr 01 17:57:37 CST 2017
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}