package com.ums.management.core.model;

public class SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.cfg_key
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    private String cfgKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.cfg_value
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    private String cfgValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.cfg_key
     *
     * @return the value of sys_config.cfg_key
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public String getCfgKey() {
        return cfgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.cfg_key
     *
     * @param cfgKey the value for sys_config.cfg_key
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public void setCfgKey(String cfgKey) {
        this.cfgKey = cfgKey == null ? null : cfgKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.cfg_value
     *
     * @return the value of sys_config.cfg_value
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public String getCfgValue() {
        return cfgValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.cfg_value
     *
     * @param cfgValue the value for sys_config.cfg_value
     *
     * @mbggenerated Thu Aug 10 15:47:04 CST 2017
     */
    public void setCfgValue(String cfgValue) {
        this.cfgValue = cfgValue == null ? null : cfgValue.trim();
    }
}