package com.ums.management.core.model;

public class UserOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_org.id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_org.user_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_org.org_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    private Integer orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_org.id
     *
     * @return the value of user_org.id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_org.id
     *
     * @param id the value for user_org.id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_org.user_id
     *
     * @return the value of user_org.user_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_org.user_id
     *
     * @param userId the value for user_org.user_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_org.org_id
     *
     * @return the value of user_org.org_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_org.org_id
     *
     * @param orgId the value for user_org.org_id
     *
     * @mbggenerated Wed Apr 05 13:20:15 CST 2017
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}